#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "local"
hooks = [
    { id = "biome", name = "biome check", entry = "npx biome check --no-errors-on-unmatched --files-ignore-unknown=true", language = "system", types = ["text"] },
]
