// Generated by tools/avb/generate-cast-bounds.ts from public/assets/avatars/manifest.json.

export interface CastBounds {
	name: string;
	type: "simple" | "complex";
	faces: number;
	torsos: number;
	bodies: number;
}

// keyed by avatarID, which the wire and stored history speak; ids never renumber
export const CAST_BOUNDS: Readonly<Record<number, CastBounds>> = {
	1: { name: "anna", type: "complex", faces: 18, torsos: 16, bodies: 0 },
	2: { name: "bolo", type: "complex", faces: 12, torsos: 11, bodies: 0 },
	3: { name: "connor", type: "simple", faces: 0, torsos: 0, bodies: 15 },
	4: { name: "denise", type: "complex", faces: 18, torsos: 9, bodies: 0 },
	5: { name: "hugh", type: "complex", faces: 14, torsos: 12, bodies: 0 },
	6: { name: "susan", type: "complex", faces: 20, torsos: 11, bodies: 0 },
	7: { name: "armando", type: "complex", faces: 12, torsos: 11, bodies: 0 },
	8: { name: "cro", type: "complex", faces: 13, torsos: 13, bodies: 0 },
	9: { name: "dan", type: "complex", faces: 17, torsos: 11, bodies: 0 },
	10: { name: "glenda", type: "simple", faces: 0, torsos: 0, bodies: 1 },
	11: { name: "jordan", type: "simple", faces: 0, torsos: 0, bodies: 14 },
	12: { name: "lance", type: "complex", faces: 11, torsos: 11, bodies: 0 },
	13: { name: "lynnea", type: "complex", faces: 17, torsos: 18, bodies: 0 },
	14: { name: "margaret", type: "complex", faces: 20, torsos: 13, bodies: 0 },
	15: { name: "mike", type: "complex", faces: 10, torsos: 8, bodies: 0 },
	16: { name: "pedagog", type: "simple", faces: 0, torsos: 0, bodies: 1 },
	17: { name: "rainbow", type: "simple", faces: 0, torsos: 0, bodies: 1 },
	18: { name: "tiki", type: "complex", faces: 20, torsos: 12, bodies: 0 },
	19: { name: "tongtyed", type: "complex", faces: 13, torsos: 13, bodies: 0 },
	20: { name: "tux", type: "simple", faces: 0, torsos: 0, bodies: 1 },
	21: { name: "waf", type: "simple", faces: 0, torsos: 0, bodies: 1 },
	22: { name: "xeno", type: "complex", faces: 13, torsos: 14, bodies: 0 },
	23: { name: "buck", type: "complex", faces: 14, torsos: 13, bodies: 0 },
	24: { name: "kirby", type: "complex", faces: 14, torsos: 14, bodies: 0 },
	25: { name: "veronica", type: "complex", faces: 12, torsos: 15, bodies: 0 },
	26: { name: "kevin", type: "complex", faces: 13, torsos: 15, bodies: 0 },
	27: { name: "kwensa", type: "complex", faces: 16, torsos: 18, bodies: 0 },
	28: { name: "maynard", type: "complex", faces: 15, torsos: 26, bodies: 0 },
	29: { name: "rebecca", type: "complex", faces: 19, torsos: 24, bodies: 0 },
	30: { name: "sage", type: "complex", faces: 20, torsos: 17, bodies: 0 },
	31: { name: "scotty", type: "complex", faces: 24, torsos: 9, bodies: 0 },
};
