// Generated by tools/avb/generate-cast-bounds.ts from public/assets/avatars/manifest.json; index is avatarID - 1.

export interface CastBounds {
	type: "simple" | "complex";
	faces: number;
	torsos: number;
	bodies: number;
}

export const CAST_BOUNDS: readonly CastBounds[] = [
	// anna
	{ type: "complex", faces: 18, torsos: 16, bodies: 0 },
	// bolo
	{ type: "complex", faces: 12, torsos: 11, bodies: 0 },
	// connor
	{ type: "simple", faces: 0, torsos: 0, bodies: 15 },
	// denise
	{ type: "complex", faces: 18, torsos: 9, bodies: 0 },
	// hugh
	{ type: "complex", faces: 14, torsos: 12, bodies: 0 },
	// susan
	{ type: "complex", faces: 20, torsos: 11, bodies: 0 },
	// armando
	{ type: "complex", faces: 12, torsos: 11, bodies: 0 },
	// cro
	{ type: "complex", faces: 13, torsos: 13, bodies: 0 },
	// dan
	{ type: "complex", faces: 17, torsos: 11, bodies: 0 },
	// glenda
	{ type: "simple", faces: 0, torsos: 0, bodies: 1 },
	// jordan
	{ type: "simple", faces: 0, torsos: 0, bodies: 14 },
	// lance
	{ type: "complex", faces: 11, torsos: 11, bodies: 0 },
	// lynnea
	{ type: "complex", faces: 17, torsos: 18, bodies: 0 },
	// margaret
	{ type: "complex", faces: 20, torsos: 13, bodies: 0 },
	// mike
	{ type: "complex", faces: 10, torsos: 8, bodies: 0 },
	// pedagog
	{ type: "simple", faces: 0, torsos: 0, bodies: 1 },
	// rainbow
	{ type: "simple", faces: 0, torsos: 0, bodies: 1 },
	// tiki
	{ type: "complex", faces: 20, torsos: 12, bodies: 0 },
	// tongtyed
	{ type: "complex", faces: 13, torsos: 13, bodies: 0 },
	// tux
	{ type: "simple", faces: 0, torsos: 0, bodies: 1 },
	// waf
	{ type: "simple", faces: 0, torsos: 0, bodies: 1 },
	// xeno
	{ type: "complex", faces: 13, torsos: 14, bodies: 0 },
	// buck
	{ type: "complex", faces: 14, torsos: 13, bodies: 0 },
	// kirby
	{ type: "complex", faces: 14, torsos: 14, bodies: 0 },
	// veronica
	{ type: "complex", faces: 12, torsos: 15, bodies: 0 },
	// kevin
	{ type: "complex", faces: 13, torsos: 15, bodies: 0 },
	// kwensa
	{ type: "complex", faces: 16, torsos: 18, bodies: 0 },
	// maynard
	{ type: "complex", faces: 15, torsos: 26, bodies: 0 },
	// rebecca
	{ type: "complex", faces: 19, torsos: 24, bodies: 0 },
	// sage
	{ type: "complex", faces: 20, torsos: 17, bodies: 0 },
	// scotty
	{ type: "complex", faces: 24, torsos: 9, bodies: 0 },
];
