// Node CLI: derive the worker's compact record-count table from the committed manifest.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

interface ManifestAvatar {
	avatarID: number;
	name: string;
	type: "simple" | "complex";
	faces: unknown[];
	torsos: unknown[];
	bodies: unknown[];
}

const defaultManifest = fileURLToPath(
	new URL("../../public/assets/avatars/manifest.json", import.meta.url),
);
const defaultOutput = fileURLToPath(
	new URL("../../src/protocol/castBounds.ts", import.meta.url),
);

const manifestPath = resolve(process.argv[2] ?? defaultManifest);
const output = resolve(process.argv[3] ?? defaultOutput);
const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as {
	avatars: ManifestAvatar[];
};

const rows = manifest.avatars
	.slice()
	.sort((a, b) => a.avatarID - b.avatarID)
	.map(
		(avatar) =>
			`\t// ${avatar.name}\n\t{ type: "${avatar.type}", faces: ${avatar.faces.length}, torsos: ${avatar.torsos.length}, bodies: ${avatar.bodies.length} },`,
	);

writeFileSync(
	output,
	`// Generated by tools/avb/generate-cast-bounds.ts from public/assets/avatars/manifest.json; index is avatarID - 1.

export interface CastBounds {
	type: "simple" | "complex";
	faces: number;
	torsos: number;
	bodies: number;
}

export const CAST_BOUNDS: readonly CastBounds[] = [
${rows.join("\n")}
];
`,
);
process.stdout.write(`${rows.length} avatars -> ${output}\n`);
